#ifndef SCIENTIFICCOMPUTING_PRODUCERCONSUMERTHREADS_DATAFLOW_HPP
#define SCIENTIFICCOMPUTING_PRODUCERCONSUMERTHREADS_DATAFLOW_HPP

#include "dataflow/Consumer.hpp"
#include "dataflow/Producer.hpp"
#include "dataflow/Queue.hpp"

#endif // SCIENTIFICCOMPUTING_PRODUCERCONSUMERTHREADS_DATAFLOW_HPP